# Te

## Quickstart:
Following are the.

Note: This is a same.
     
      Add 
      Add 
    

1. Download cript from [dww] (https://courses.grainger.illinois.edu/cs126/sp2020/notes/cmake/). 

2. Execute the SDK ins (dada)

3. Clone
 
   src :        Source files 
   inc :        Header Files 
   lib :        Prebuilt libraries fo linking target binary
 
   
4. Set up
   source /pat
   For Ex. source 

5. Go to 
   ./bui.sh
   This script 

6. Build
   cmake ..
   make




 

## GT
st is


## Why est?

Indep : Goog


## ggg
T:  It is us.

E():     It 

Fix : Cs.

## Basic Concepts:


A statements 
        

        fa : It abor
        non  : it 




### Fn          ### Non                          ### me
A;	        EX	                         nnn

