#Quickstart:
sample file.

Note: This is a sample .
     
      Add source cod
      Add respective head
      Add libra
      Modify CMa
      Once all these changes are done, follow the next steps.

1. Download script from [link] (https://courses.grainger.illinois.edu/cs126/sp2020/notes/cmake/). 

2. Execute the SDK installation script and mention pat (dwdwdw)

3. Clone [this](https://courses.grainger.illinois.edu/cs126/sp2020/notes/cmake/) repo. Sample test code is available in src directory. 
   src :        Source files 
   inc :        Header Files 
   lib :        Prebuilt libraries fo linking target binary
